### ISSUE TITLE
pre-Alpha checklist

### ISSUE THREAD

**Issue by vykster** [brighthive/data-resource-api#35]
- [ ] Documentation: Complete README starter template
  - [ ] GitHub repo is public (or documented exception in README)
  - [ ] License exists (MIT License, or other license with documented exception to MIT in README)
- [ ] Tests: Some unit tests written
  - [ ] Configure coverage tools (Coveralls.io + pytest.cov)
  - [ ] Configure continuous integration (Circle CI)
  - [ ] Configure style checking (aka code formatting) tool (flake8)
- [ ] Contribute: Ability for teammate to quickly contribute 
  - [ ] “Getting Started” in README
  - [ ] Docker setup: Dockerfile
  - [ ] Docker setup: docker-compose.yml (or docker-compose-dev.yml)
